### ISSUE TITLE
Adding a project to the list of forks?

### ISSUE THREAD

**Issue by eitansuez** [spring-petclinic/spring-petclinic.github.io#15]
Hello,
A couple of months ago I developed [a variant of Spring PetClinic Cloud for Istio](https://github.com/eitansuez/spring-petclinic-istio).
I'd like to know if it's possible to list this variant among the list of forks, to make it easier for developers to find.
Thanks in advance, / Eitan

**Comment by arey** [comment]
Hello Eitan,

Sure it’s possible to reference your istio version to the Spring Petclinic website trough a Pull Request. 
I know that Istio could handle a lot of things. I can see it in action now. It’s a great work !
If you want, I could propose you to move on your fork to the Spring Petclinic community. Let me know and I add you as member.

Regards

Antoine Rey


Le 5 juin 2023 à 18:51:43, Eitan Suez ***@***.***) a écrit:

Hello,
A couple of months ago I developed a variant of Spring PetClinic Cloud for Istio.
I'd like to know if it's possible to list this variant among the list of forks, to make it easier for developers to find.
Thanks in advance, / Eitan

**Comment by eitansuez** [comment]
Hi Antoine,

Thank you for the offer to join the Spring PetClinic community.  Yes, please do add me as a member.
I just submitted [a PR adding my repo to the list of forks](https://github.com/spring-petclinic/spring-petclinic.github.io/pull/16).
Happy to move the repo to the community GitHub org if that's more appropriate.

Best, / Eitan

**Comment by arey** [comment]
Hi Eitan,

I’ve granted as org member. Welcome :-D
I let you move your repo and update your PR link to the new location.

Regards

Antoine


Le 6 juin 2023 à 18:28:37, Eitan Suez ***@***.***) a écrit:

Hi Antoine,

Thank you for the offer to join the Spring PetClinic community. Yes, please do add me as a member.
I just submitted a PR adding my repo to the list of forks.
Happy to move the repo to the community GitHub org if that's more appropriate.

Best, / Eitan

**Comment by eitansuez** [comment]
Super.  Invite accepted, repo placed in spring-petclinic organization, and
PR is updated.  Thanks! / Eitan

**Comment by arey** [comment]
Thanks Eitan. Il will see your presentation video https://youtu.be/1UybZGws4m8

**Comment by eitansuez** [comment]
Thank you Antoine!

**Comment by arey** [comment]
You're welcome :D
